# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "terraform-state-us-east1-my-deployments-2"
    prefix = "production/network/ssl-policy/terraform.tfstate"
  }
}
